#
# Copyright (C) 2025 - 2026 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: e2e-tests

on:
  pull_request:
    types: [labeled, synchronize, opened, ready_for_review, reopened]

jobs:
  # Dedicated step to build the extension image
  build-container:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'area/ci/e2e') }}
    name: Build Extension Image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build Image and Extract Files
        id: build-image
        run: |
          podman build -t local_image -f build/Containerfile ./
          CONTAINER_ID=$(podman create localhost/local_image --entrypoint "")
          mkdir -p output/plugins
          podman export $CONTAINER_ID | tar -x -C output/plugins/
          podman rm -f $CONTAINER_ID
          podman rmi -f localhost/local_image:latest
      - name: Upload Extension Image Artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: extension-plugin
          path: output/plugins/

  integration-tests-pr-check:
    name: integration tests / ${{ matrix.os }}
    needs: build-container
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2025, ubuntu-24.04, macos-26 ]
    env:
      SKIP_INSTALLATION: true
      EXTENSION_PREINSTALLED: true
      PODMAN_DESKTOP_ARGS: ${{ github.workspace }}/podman-desktop
      # by default playwright cache browsers binaries in ~/.cache/ms-playwright on Linux and %USERPROFILE%\AppData\Local\ms-playwright on Windows
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/podman-desktop/pw-browsers
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Revert unprivileged user namespace restrictions in Ubuntu 24.04
        if: runner.os == 'Linux'
        run: |
          # allow unprivileged user namespace
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      # ==============================================
      # Installing Podman Desktop
      # ==============================================
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        name: Install pnpm
        with:
          run_install: false

      # Install Node.js
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24
          cache: 'pnpm'

      # Install npm packages for extension
      - name: Execute pnpm in Extension
        run: pnpm install

      # Extract @podman-desktop/api version used (and store to $GITHUB_OUTPUT)
      - name: Extract @podman-desktop/api version
        id: pd-api-version
        shell: bash
        run: |
          # Using pnpm list to get the resolved version (E.g. getting 1.15.0 when ^1.15.0)
          export PD_VERSION=$(pnpm list -C packages/extension/ --json | jq -r '.[0].devDependencies."@podman-desktop/api".version')
          echo "PD_VERSION=$PD_VERSION" >> $GITHUB_OUTPUT
          echo "Using @podman-desktop/api $PD_VERSION"

      # Check cache for existing podman-desktop
      - name: Cache Podman Desktop
        id: cache-pd
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ${{ github.workspace }}/podman-desktop
          key: pd-${{ steps.pd-api-version.outputs.PD_VERSION }}-${{ runner.os }}

      # If not cached, download Podman Desktop repository based on version defined in package.json
      - name: Download Podman Desktop
        if: steps.cache-pd.outputs.cache-hit != 'true'
        shell: bash
        env:
          PD_VERSION: ${{ steps.pd-api-version.outputs.PD_VERSION }}
        run: |
          echo "Downloading PD desktop to ${{ github.workspace }}/podman-desktop"
          # Stable release are available podman-desktop/podman-desktop
          # Prerelease are available under podman-desktop/prereleases
          if [[ "$PD_VERSION" =~ - ]]; then
            curl -sL "https://github.com/podman-desktop/prereleases/archive/refs/tags/v$PD_VERSION.tar.gz" | tar xvz
          else
            curl -sL "https://github.com/podman-desktop/podman-desktop/archive/refs/tags/v$PD_VERSION.tar.gz" | tar xvz
          fi
          # Move the extracted folder to the podman-desktop folder
          mv podman-desktop-$PD_VERSION/ podman-desktop/

      # Install and build podman-desktop
      - name: If not cached, install pnpm deps and build Podman Desktop
        if: steps.cache-pd.outputs.cache-hit != 'true'
        shell: bash
        working-directory: ${{ github.workspace }}/podman-desktop
        run: |
          pnpm install
          pnpm test:e2e:build

      # Install the extension
      - name: Download Extension Plugin
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: extension-plugin
          path: tests/playwright/tests/playwright/output/kubernetes-dashboard-tests/plugins/

      # Run envtest cluster
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '1.25'

      - name: install envtest-start and setup-envtest binaries
        shell: bash
        run: |
          go install github.com/feloy/envtest-start@v0.1.0
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@release-0.22

      - name: install envtest with latest kubernetes version with setup-envtest
        id: setup-envtest
        shell: bash
        run: |
          export KUBEBUILDER_ASSETS=$(setup-envtest use -p path)
          echo "KUBEBUILDER_ASSETS=$KUBEBUILDER_ASSETS" >> $GITHUB_OUTPUT

      - name: run envtest-start to start the envtest cluster with 1 user user1
        id: run-envtest
        env:
          KUBEBUILDER_ASSETS: ${{ steps.setup-envtest.outputs.KUBEBUILDER_ASSETS }}
        shell: bash
        run: |
          KUBECONFIG='${{ runner.temp }}/envtest-kubeconfig'
          KUBECONFIG_USER1='${{ runner.temp }}/user1-kubeconfig'
          envtest-start --users 1 "$KUBECONFIG" &
          ENVTEST_START_PID=$!
          echo "ENVTEST_START_PID=$ENVTEST_START_PID" >> $GITHUB_OUTPUT
          echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_OUTPUT
          echo "KUBECONFIG_USER1=$KUBECONFIG_USER1" >> $GITHUB_OUTPUT

      - name: check cluster is accessible, should show a service named "kubernetes"
        env:
          KUBEBUILDER_ASSETS: ${{ steps.setup-envtest.outputs.KUBEBUILDER_ASSETS }}
          KUBECONFIG: '${{ steps.run-envtest.outputs.KUBECONFIG }}'
        shell: bash
        run: |
          "$KUBEBUILDER_ASSETS/kubectl" get all | grep "service/kubernetes"

      - name: Install kubectl on macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew install kubectl
          kubectl version --client

      # Run tests
      - name: Run Integration tests
        shell: bash
        run: |
          cp "${KUBECONFIG}" ./tests/resources/envtest-kubeconfig
          cp "${KUBECONFIG_USER1}" ./tests/resources/envtest-kubeconfig-user1
          pnpm test:e2e:integration
        env:
          NODE_OPTIONS: --no-experimental-strip-types
          KUBEBUILDER_ASSETS: ${{ steps.setup-envtest.outputs.KUBEBUILDER_ASSETS }}
          KUBECONFIG: ${{ steps.run-envtest.outputs.KUBECONFIG }}
          KUBECONFIG_USER1: ${{ steps.run-envtest.outputs.KUBECONFIG_USER1 }}

      - name: stop envtest cluster on non-macOS
        if: always() && runner.os != 'macOS'
        env:
          ENVTEST_START_PID: ${{ steps.run-envtest.outputs.ENVTEST_START_PID }}
        shell: bash
        # These commands are working on both Linux and Windows, change carefully
        run: |
          kill ${ENVTEST_START_PID}
          timeout 10s bash -c "while ps | grep envtest-start > /dev/null; do sleep 1; done"

      - name: stop envtest cluster on macOS
        if: always() && runner.os == 'macOS'
        env:
          ENVTEST_START_PID: ${{ steps.run-envtest.outputs.ENVTEST_START_PID }}
        shell: bash
        run: |
          kill ${ENVTEST_START_PID}
          brew install coreutils
          gtimeout 10s bash -c "while ps | grep envtest-start > /dev/null; do sleep 1; done"

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: always()
        with:
          name: e2e-pr-check-${{ matrix.os }}
          path: |
            tests/playwright/output/
            tests/playwright/tests/
